# Generated by Django 2.1.3 on 2018-12-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chooseClass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_number', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('id_number', models.CharField(max_length=10, unique=True)),
                ('average', models.IntegerField()),
                ('entery_year', models.CharField(max_length=4)),
                ('firstName', models.CharField(blank=True, max_length=254, null=True)),
                ('lastName', models.CharField(blank=True, max_length=254, null=True)),
                ('major', models.CharField(blank=True, max_length=254, null=True)),
                ('classes', models.ManyToManyField(blank=True, to='chooseClass.Class')),
            ],
        ),
    ]
