# Generated by Django 2.1.3 on 2018-12-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPlan', '0002_auto_20181228_1055'),
        ('login', '0002_student_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='plan',
        ),
        migrations.AddField(
            model_name='student',
            name='regPlan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rplan', to='myPlan.Plan'),
        ),
    ]
