# Generated by Django 2.1.3 on 2018-12-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classId', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('examTime', models.CharField(max_length=10)),
                ('examDay', models.CharField(blank=True, max_length=10)),
                ('courseTime', models.CharField(max_length=10)),
                ('courseDay', models.CharField(max_length=10)),
                ('capacity', models.CharField(max_length=3)),
                ('semester', models.CharField(max_length=7)),
                ('registered', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=20)),
                ('units', models.CharField(max_length=2)),
                ('havePreCourse', models.CharField(max_length=1)),
                ('havePeriCourse', models.CharField(max_length=1)),
                ('periCourse', models.ManyToManyField(blank=True, related_name='PeriCourse', to='chooseClass.Course')),
                ('preCourse', models.ManyToManyField(blank=True, related_name='PreCourse', to='chooseClass.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherId', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('teacherName', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chooseClass.Course'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chooseClass.Teacher'),
        ),
    ]
